name = "eden-api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-03-18"

[build]
command = "echo 'Done: Release Build'"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }
